# -*- coding: utf-8 -*-
"""agent.ipynb

(Original version) Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQyX66xTEgqjMeYSPLXfRWO__Zc9Y1wi
    
This file contains two classes: ChildMessagesState and LibrAIrianAgent. The purpose
of these classes overall is to establish a LangGraph based structure for our 
child reading assistant tool. 
"""

from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode, tools_condition
import pandas as pd
from typing import Dict, List, Set, Tuple
import re

# in recitation, we saw an example with Messages State,
# but that does not suit the specific needs of our project
# so we define our own below:
from typing import TypedDict, Any

class ChildMessagesState(TypedDict):
  """
  This class defines a custom State schema using TypedDict as a type hint
  to ensure that the provided keys are used.
  
  It represents the state of the conversation between the system model
  and the child at a given moment, containing all the defining information
  of that point in the conversation in defined keys.
  
  The defined keys are story_title, user_query, query_type, messages, 
  retrieve_passages, response, final_output, turn_count, unsafe, and 
  quit.
  """
  story_title: str # or None
  # the user input
  user_query: str
  # check the kind of query the user is passing
  # 0 is a query on a specific title in database
  # 1 is a query on a specific title not in database
  # 2 is a general query
  query_type: int
  # to store message history
  messages: list
  # the RAG results
  retrieve_passages: Any
  # system initial response
  response: str
  # system output after safety check
  final_output: str
  # counts how many questions have been asked
  # limit 10 to limit screen time
  turn_count: int
  # bool marker of if need to exit for safety
  unsafe: bool | None
  # bool marker of if user chooses to exit
  quit: bool | None

class LibrAIrianAgent:
  """
  This class defines the actual agent using the other classes defined in our
  project. 
  
  The agent should receive input from a user and generate a response using
  retrieved passages, ensuring safety through the use of safety filters
  and setting limits on the total number of exchanges.
  
  A langgraph graph is built using StateGraph and ChildMessageState as defined
  above to ensure a logical flow to generate output and continue a conversation.
  
  The overall order of this graph is:
    1. Get a story title
    2. Get user input
    3. Check the safety of this input
    4. Check the total number of exchanges against max number of exchanges
    5. Check the query type based on the story title
    6. Retrieve the most relevant passages (dependent on query type)
    7. Filter the retrieved passages for only safe passages
    8. Generate a reponse to the query using context passages
    9. Check the response safety before returning output
    
  If at any point the user enters "quit" as their query, the session ends.
  """
  def __init__(self, rag, llm, input_filter, output_filter, max_turns=10):
    """
    Initialize an instance of our conversational agent by building LangGraph 
    graph with nodes defined below.
    
    Args:
        rag (KidsRAG): Instance of class to create embeddings and perform passage retrieval
        llm (LLM): Instance of class to use LLM model to generate response
        input_filter (InputFilter): Instance of class to check user input safety
        output_filter (OutputFilter): Instance of class to check LLM output safety
        max_turns (int): Sets limit for number of exchanges with agent
    """
    self.rag = rag
    self.llm = llm
    self.filter_input = input_filter
    self.filter_output = output_filter
    self.max_turns = max_turns

    # create a graph builder to set nodes and edges using our messages state
    # modeled this after the example from lab 7
    graph_builder = StateGraph(ChildMessagesState)

    # add nodes, and give them the same name
    graph_builder.add_node("get_story_title", self.get_story_title)
    graph_builder.add_node("get_user_input", self.get_user_input)
    graph_builder.add_node("check_input_safety", self.check_input_safety)
    graph_builder.add_node("check_exchange_count", self.check_exchange_count)
    graph_builder.add_node("check_query_type", self.check_query_type)
    graph_builder.add_node("retrieve_passages_node", self.retrieve_passages_node)
    graph_builder.add_node("filter_retrieved_passages", self.filter_retrieved_passages)
    graph_builder.add_node("generate_response", self.generate_response)
    graph_builder.add_node("check_answer_safety", self.check_answer_safety)

    # add edges between subsequent pieces of the pipeline
    graph_builder.set_entry_point("get_story_title")
    graph_builder.add_edge("get_story_title","get_user_input")
    graph_builder.add_conditional_edges("get_user_input", 
    lambda state: "quit" if state.get("quit") else "continue",
    {"quit":END,"continue":"check_input_safety"})
    graph_builder.add_conditional_edges("check_input_safety",
    lambda state: "unsafe" if state.get("unsafe") else "safe",
    {"unsafe":END,"safe":"check_exchange_count"})
    graph_builder.add_edge("check_exchange_count", "check_query_type")
    graph_builder.add_edge("check_query_type", "retrieve_passages_node")
    graph_builder.add_edge("retrieve_passages_node", "filter_retrieved_passages")
    graph_builder.add_conditional_edges("filter_retrieved_passages", 
    lambda state: "unsafe" if state.get("unsafe") else "safe",
    {"unsafe":END,"safe":"generate_response"})
    graph_builder.add_edge("generate_response", "check_answer_safety")
    graph_builder.add_edge("check_answer_safety", END)

    self.graph = graph_builder.compile()

  # get user title
  def get_story_title(self, state: ChildMessagesState):
    """
    This is a node function that retrieves and properly formats user input
    for a story title.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict: This is a dictionary mapping story_title to new, formatted title 
        in order to update ChildMessagesState state.
    """
    user_story_title = state['story_title'].strip()
    story_title_text = user_story_title.strip('".!?')
    normalized_title = re.sub(r"[^a-z0-9 ]", "", story_title_text.lower())

    return {"story_title":normalized_title}

  # get user input

  def get_user_input(self, state: ChildMessagesState):
    """
    This is a node function that retrieves and properly formats the actual
    query from a user. It also increases turn count by 1.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict: This is a dictionary containing the updates to the state's turn count, 
        message history, and user query.
    """
    user_input = state['user_query'].strip().lower()
    
    if user_input == "quit":
        final_output = "Goodbye! Talk to you soon."
        
        message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
        
        return {"final_output":final_output,"messages":message_history,"quit":True}

    # add one to the turn count
    state['turn_count'] += 1

    # store in message history, under role of user since user input
    message_history = state['messages'] + [{"role": "user", "content": user_input}]

    return {"turn_count": state['turn_count'], "messages":message_history, "user_query":user_input}

  # check question safety --> use function from Mia's safety filtering section

  def check_input_safety(self, state: ChildMessagesState):
    """
    This is a node function that checks if the user query is safe to answer, and which returns a
    fallback response if not.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict:
            if input filter is_safe method is applied to user input and returns False:
                -A dictionary containing final_output (set to fallback message), an 
                updated messages history, and "unsafe" key mapped to True
            else:
                -A dictionary that maps the "unsafe" key to False to update the state
    """
    user_input = state['user_query']

    # use safety filtering to check if input is safe
    # if it is not, fall back on safe response
    if self.filter_input.is_safe(user_input) == False:
      final_output = """I'm sorry, that response is not safe for me to answer.
      Please ask a trusted adult for further information on this question.
      What else would you like to learn about?"""

      # add system response to history as it is final response automatically
      messages_history = state['messages'] + [{"role": "assistant", "content":final_output}]

      return {"final_output":final_output,"messages":messages_history, "unsafe":True}

    return {"unsafe":False}

  def check_query_type(self, state: ChildMessagesState):
    """
    This is a node function that checks the user query type, depending on story_title.
    
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict:
            if the story title is "general":
                -A dictionary that maps key "query_type" to 2
            else if the story title is not "general" and is in RAG titles list:
                -A dictionary that maps key "query_type" to 0
            else:
                -A dictionary that maps key "query_type" to 1
    """
    # check the kind of query the user is passing
    # 0 is a query on a specific title in database
    # 1 is a query on a specific title not in database
    # 2 is a general query

    user_story_title = state['story_title']

    if user_story_title == "general":
      return {"query_type":2}

    if user_story_title in self.rag.passages_df['title'].unique():
        return {"query_type":0}

    return {"query_type":1}

  # make sure that user is not spending too long on system
  # within certain time period? TODO

  def check_exchange_count(self, state: ChildMessagesState):
    """
    This is a node function that checks whether the user has reached the exchange limit,
    and returns a fallback safe output if so.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict: 
            if turn_count is over the max number of turns (default 10):
                -A dictionary setting key final_output to fallback response, updating
                messages with message history, and marking "unsafe" key as True
            else:
                -A dictionary setting key "unsafe" to False
                
    """
    # if we have reached limit, return safe message as final output
    if state['turn_count'] >= self.max_turns:
      final_output = "It was great talking to you! However, your librAIrian \
      needs to take a break. Come back later to ask more questions!"

      # add to history
      message_history = state['messages'] + [{"role":"assistant", "content":final_output}]

      return {"final_output":final_output, "messages":message_history, "unsafe":True}

    return {"unsafe":False}

  # retrieve relevant passages

  def retrieve_passages_node(self, state: ChildMessagesState):
    """
    This is a node function that uses the RAG class to retrieve the most relevant
    passages, with behavior depending on query_type. If query_type is 0 or 2, the 
    whole subset of passages is used, while if query_type equals 1, only the subset of
    passages and embeddings which come from the same title are used.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict: This is a dictionary containing the update to the state's retrieve_passages
        with the most relevant retrieved passages to the user query.
    """
    # using rag to retrieve passages
    if state['query_type'] == 0:
      df = self.rag.passages_df[self.rag.passages_df['title'] == state['story_title']]
      embeddings = self.rag.embeddings[df.index]
      results = self.rag.retrieve_passages(state['user_query'], subset_embeddings=embeddings, subset_df=df)
    else:
      results = self.rag.retrieve_passages(state['user_query'])

    state['retrieve_passages'] = results

    return {'retrieve_passages':results}

  # filter retrieved passages
  
  def filter_retrieved_passages(self, state: ChildMessagesState):
    """
    This is a node function that checks the safety of the content in the retrieved passages.
    It checks each passage for safety and removes it from the context if it is unsafe. If no
    safe passages are returned, a fallback safe response is used as the final output.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict:
            if filtered.empty == True (there are no safe passages):
                -A dictionary that sets the state's final output, message history, and marks
                "unsafe" as True
            else:
                -A dictionary that updates the retrieved passages to only the safe ones and 
                marks "unsafe" as False
    """
    filtered = self.rag.filter_passages(state['retrieve_passages'], filter_obj=self.filter_output)
    if filtered.empty == True:
        final_output = "I'm sorry, the passages I found to answer that question were not safe. Please try a different question."
        
        state['retrieve_passages'] = filtered
        
        # add this to message history for system
        message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
        state['final_output'] = final_output
        
        return {"final_output":final_output, "messages":message_history, 'unsafe':True}
        
    state['retrieve_passages'] = filtered
    return {'retrieve_passages': filtered, "unsafe":False}

  # generate response

  def generate_response(self, state: ChildMessagesState):
    """
    This is a node function that generates the response from the LLM using the query,
    retrieved passages, and message history.Depending on query type, a query type disclaimer 
    will be added to the final output, letting the user know if their query is being answered 
    based on the whole corpus or a subset.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict: This is a dictionary containing the response generated by the LLM.
    """
    # generate_answer from ada
    # call it using the query, the results of RAG, and message history

    # add dislaimer depending on input type
    query_type_disclaimer= ""

    if state["query_type"] == 0:
       query_type_disclaimer = """That story is in our library!
       Answering your question based on this title...
       """

    elif state["query_type"] == 1:
       query_type_disclaimer = """The specific title you were wondering about is not in our library!
       This answer is based on similar available stories:
       """

    elif state["query_type"] == 2:
       query_type_disclaimer = "Answering general query based on related stories..."

    response = self.llm.ask_gpt(
        state['user_query'],
        state['retrieve_passages'],
        state['messages'],
        query_type_disclaimer=query_type_disclaimer
      )

    state['response'] = response

    return {"response":response}

  # validate response safety

  def check_answer_safety(self, state: ChildMessagesState):
    """
    This is node function that ensures the LLM generated output is safe for children, 
    and which generates a fallback response if not, after making two more attempts to 
    generate a safe response.
    
    Args:
        state (ChildMessagesState): the current state of the conversation
    
    Returns:
        dict:
            if output filter is_output_safe method is applied to LLM output and returns False
            even after three attempts:
                -A dictionary containing final_output (set to fallback message), an 
                updated messages history, and "unsafe" key mapped to True
            else if is_output_safe method is applied to LLM output and returns True:
                -A dictionary containing the generated final output, updated messages history,
                and "unsafe" key set to True
    """
    # if answer is unsafe, only try again a set number of times
    max_attempts = 3

    attempts = 0
    while attempts < max_attempts:
      # if the output is safe, then the draft response is the final response
      # output safety check from Mia's safety filtering layer
      if self.filter_output.is_output_safe(state['response']) == True:
        final_output = state['response']
        # add to message history
        message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
        return {"final_output":final_output, "messages":message_history, "unsafe":False}

      # output safety check from Mia's safety filtering layer
      else:
        print("""Please wait one second for me to rephrase my response!
        My initial response was not safe.""")

        # try generating a new answer
        # and then reenter this loop
        query_type_disclaimer= ""
        if state["query_type"] == 0:
          query_type_disclaimer = """That story is in our library!
          Answering your question based on this title...
          """

        elif state["query_type"] == 1:
          query_type_disclaimer = """The specific title you were wondering about is not in our library!
          This answer is based on similar available stories:
          """

        elif state["query_type"] == 2:
          query_type_disclaimer = "Answering general query based on related stories..."

        response = self.llm.ask_gpt(
          state['user_query'],
          state['retrieve_passages'],
          state['messages'],
          query_type_disclaimer=query_type_disclaimer
        )
        attempts += 1

    # if we exit the while loop because exceeded max attempts
    # give back up message
    final_output = "I'm sorry, I reached the maximum number of attempts to \n  generate a safe response. Please try another question."

    # add this to message history for system
    message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
    state['final_output'] = final_output
    
    return {"final_output":final_output, "messages":message_history, "unsafe":True}

  def run(self, story_title, user_query):
    """
    A function to create a ChildMessagesState object and use it to invoke class defined 
    above to generate output for a user query.
    
    Args:
        story_title (str): The story title provided by user, or "general"
        user_query (str): The input/question provided by user
    
    Returns:
        A string containing the final generated output. 
    """
    # initialize state object
    state = ChildMessagesState(
        story_title=story_title,
        user_query=user_query,
        messages=[],
        retrieve_passages=None,
        response="",
        final_output="",
        turn_count=0
    )

    # set user query to input from above
    state['story_title'] = story_title
      
    # set user query to input from above
    state['user_query'] = user_query

    # generate response by invoking the graph we built
    output = self.graph.invoke(state)

    # return the final result
    return output['final_output']