# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQyX66xTEgqjMeYSPLXfRWO__Zc9Y1wi
"""

from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode, tools_condition
import pandas as pd
from typing import Dict, List, Set, Tuple
import re

# in recitation, we saw an example with Messages State,
# but that does not suit the specific needs of our project
# so we define our own below:
from typing import TypedDict, Any

class ChildMessagesState(TypedDict):
    story_title: str # or None
    # the user input
    user_query: str
    # check the kind of query the user is passing
    # 0 is a query on a specific title in database
    # 1 is a query on a specific title not in database
    # 2 is a general query
    query_type: int
    # to store message history
    # TODO: only store history up to a certain amount?
    # then reset
    messages: list
    # the RAG results
    retrieve_passages: Any
    # system initial response
    response: str
    # system output after safety check
    final_output: str
    # counts how many questions have been asked
    # limit 10 to limit screen time
    turn_count: int
    # bool marker of if need to exit for safety
    unsafe: bool | None
    # bool marker of if user chooses to exit
    quit: bool | None

class LibrAIrianAgent:
  def __init__(self, rag, llm, input_filter, output_filter, max_turns=10):
    self.rag = rag
    self.llm = llm
    self.filter_input = input_filter
    self.filter_output = output_filter
    self.max_turns = max_turns

    # create a graph builder to set nodes and edges using our messages state
    # modeled this after the example from lab 7
    graph_builder = StateGraph(ChildMessagesState)

    # add nodes, and give them the same name
    # get story title
    graph_builder.add_node("get_story_title", self.get_story_title)
    # get user input
    graph_builder.add_node("get_user_input", self.get_user_input)
    # pass user input through the input safety filter check
    graph_builder.add_node("check_input_safety", self.check_input_safety)
    # check number of turns that user had already taken before generating output
    graph_builder.add_node("check_exchange_count", self.check_exchange_count)
    # call existing RAG function using query
    graph_builder.add_node("check_query_type", self.check_query_type)
    # use existing RAG function to retrieve passages
    graph_builder.add_node("retrieve_passages_node", self.retrieve_passages_node)
    # do internal filter of these passages to make sure that they are safe enough for children
    graph_builder.add_node("filter_retrieved_passages", self.filter_retrieved_passages)
    # generate response 
    graph_builder.add_node("generate_response", self.generate_response)
    # pass generated output through output safety filtering layer
    graph_builder.add_node("check_answer_safety", self.check_answer_safety)

    # add edges between subsequent pieces of the pipeline
    graph_builder.set_entry_point("get_story_title")
    graph_builder.add_edge("get_story_title","get_user_input")
    graph_builder.add_conditional_edges("get_user_input", 
    lambda state: "quit" if state.get("quit") else "continue",
    {"quit":END,"continue":"check_input_safety"})
    graph_builder.add_conditional_edges("check_input_safety",
    lambda state: "unsafe" if state.get("unsafe") else "safe",
    {"unsafe":END,"safe":"check_exchange_count"})
    graph_builder.add_edge("check_exchange_count", "check_query_type")
    graph_builder.add_edge("check_query_type", "retrieve_passages_node")
    graph_builder.add_edge("retrieve_passages_node", "filter_retrieved_passages")
    graph_builder.add_conditional_edges("filter_retrieved_passages", 
    lambda state: "unsafe" if state.get("unsafe") else "safe",
    {"unsafe":END,"safe":"generate_response"})
    graph_builder.add_edge("generate_response", "check_answer_safety")
    graph_builder.add_edge("check_answer_safety", END)

    self.graph = graph_builder.compile()

  # get user title
  def get_story_title(self, state: ChildMessagesState):
    user_story_title = state['story_title'].strip()
    story_title_text = user_story_title.strip('".!?')
    normalized_title = re.sub(r"[^a-z0-9 ]", "", story_title_text.lower())

    return {"story_title":normalized_title}

  # get user input
  def get_user_input(self, state: ChildMessagesState):
    user_input = state['user_query'].strip().lower()
    
    if user_input == "quit":
        final_output = "Goodbye! Talk to you soon."
        
        message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
        
        return {"final_output":final_output,"messages":message_history,"quit":True}

    # add one to the turn count
    state['turn_count'] += 1

    # store in message history, under role of user since user input
    message_history = state['messages'] + [{"role": "user", "content": user_input}]

    return {"turn_count": state['turn_count'], "messages":message_history, "user_query":user_input}

  # check question safety --> use function from Mia's safety filtering section

  def check_input_safety(self, state: ChildMessagesState):
    user_input = state['user_query']

    # use safety filtering to check if input is safe
    # if it is not, fall back on sfae response
    if self.filter_input.is_safe(user_input) == False:
      final_output = """I'm sorry, that response is not safe for me to answer.
      Please ask a trusted adult for further information on this question.
      What else would you like to learn about?"""

      # add system response to history as it is final response automatically
      messages_history = state['messages'] + [{"role": "assistant", "content":final_output}]

      return {"final_output":final_output,"messages":messages_history, "unsafe":True}

    return {"unsafe":False}

  def check_query_type(self, state: ChildMessagesState):
    # check the kind of query the user is passing
    # 0 is a query on a specific title in database
    # 1 is a query on a specific title not in database
    # 2 is a general query

    user_story_title = state['story_title']

    if user_story_title == "general":
      return {"query_type":2}

    if user_story_title in self.rag.passages_df['title'].unique():
        return {"query_type":0}

    return {"query_type":1}

  # make sure that user is not spending too long on system
  # within certain time period? TODO

  def check_exchange_count(self, state: ChildMessagesState):

    # if we have reached limit, return safe message as final output
    if state['turn_count'] >= 10:
      final_output = "It was great talking to you! However, your librAIrian \
      needs to take a break. Come back later to ask more questions!"

      # add to history
      message_history = state['messages'] + [{"role":"assistant", "content":final_output}]

      return {"final_output":final_output, "messages":message_history, "unsafe":True}

    return {"unsafe":False}

  # retrieve relevant passages

  def retrieve_passages_node(self, state: ChildMessagesState):
    # using rag to retrieve passages
    if state['query_type'] == 0:
      df = self.rag.passages_df[self.rag.passages_df['title'] == state['story_title']]
      embeddings = self.rag.embeddings[df.index]
      results = self.rag.retrieve_passages(state['user_query'], subset_embeddings=embeddings, subset_df=df)
    else:
      results = self.rag.retrieve_passages(state['user_query'])

    state['retrieve_passages'] = results

    return {'retrieve_passages':results}

  # filter retrieved passages
  
  def filter_retrieved_passages(self, state: ChildMessagesState):
    filtered = self.rag.filter_passages(state['retrieve_passages'], filter_obj=self.filter_output)
    if filtered.empty == True:
        final_output = "I'm sorry, the passages I found to answer that question were not safe. Please try a different question."
        
        state['retrieve_passages'] = filtered
        
        # add this to message history for system
        message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
        state['final_output'] = final_output
        
        return {"final_output":final_output, "messages":message_history, 'unsafe':True}
        
    state['retrieve_passages'] = filtered
    return {'retrieve_passages': filtered, "unsafe":False}

  # generate response

  def generate_response(self, state: ChildMessagesState):
    # generate_answer from ada
    # call it using the query, the results of RAG, and message history

    # add dislaimer depending on input type
    query_type_disclaimer= ""

    if state["query_type"] == 0:
       query_type_disclaimer = """That story is in our library!
       Answering your question based on this title...
       """

    elif state["query_type"] == 1:
       query_type_disclaimer = """The specific title you were wondering about is not in our library!
       This answer is based on similar available stories:
       """

    elif state["query_type"] == 2:
       query_type_disclaimer = "Answering general query based on related stories..."

    response = self.llm.ask_gpt(
        state['user_query'],
        state['retrieve_passages'],
        state['messages'],
        query_type_disclaimer=query_type_disclaimer
      )

    state['response'] = response

    return {"response":response}

  # validate response safety

  def check_answer_safety(self, state: ChildMessagesState):
    # if answer is unsafe, only try again a set number of times
    max_attempts = 3

    attempts = 0
    while attempts < max_attempts:
      # if the output is safe, then the draft response is the final response
      # output safety check from Mia's safety filtering layer
      if self.filter_output.is_output_safe(state['response']) == True:
        final_output = state['response']
        # add to message history
        message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
        return {"final_output":final_output, "messages":message_history, "unsafe":False}

      # output safety check from Mia's safety filtering layer
      else:
        print("""Please wait one second for me to rephrase my response!
        My initial response was not safe.""")

        # try generating a new answer
        # and then reenter this loop
        query_type_disclaimer= ""
        if state["query_type"] == 0:
          query_type_disclaimer = """That story is in our library!
          Answering your question based on this title...
          """

        elif state["query_type"] == 1:
          query_type_disclaimer = """The specific title you were wondering about is not in our library!
          This answer is based on similar available stories:
          """

        elif state["query_type"] == 2:
          query_type_disclaimer = "Answering general query based on related stories..."

        response = self.llm.ask_gpt(
          state['user_query'],
          state['retrieve_passages'],
          state['messages'],
          query_type_disclaimer=query_type_disclaimer
        )
        attempts += 1

    # if we exit the while loop because exceeded max attempts
    # give back up message
    final_output = "I'm sorry, I reached the maximum number of attempts to \n  generate a safe response. Please try another question."

    # add this to message history for system
    message_history = state['messages'] + [{"role": "assistant", "content": final_output}]
    state['final_output'] = final_output
    
    return {"final_output":final_output, "messages":message_history, "unsafe":True}

  def run(self, user_query):
    # initialize state object
      state = ChildMessagesState(
          story_title="general",
          user_query=user_query,
          messages=[],
          retrieve_passages=None,
          response="",
          final_output="",
          turn_count=0
      )

      # set user query to input from above
      state['user_query'] = user_query

      # generate response by invoking the graph we built
      output = self.graph.invoke(state)

      # return the final result
      return output['final_output']
