# -*- coding: utf-8 -*-
"""KidAI_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPV06ZZxcRggjpsAoL_VvECBbMcZ2m1L

# EDA and Visualization
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/gdrive')

"""## Children Stories Text Corpus Dataset"""

with open('/content/gdrive/MyDrive/cleaned_merged_fairy_tales_without_eos.txt', 'r', encoding='utf-8') as f:
    text_data = f.read()

# split text data
sections = text_data.split("\n\n")

titles = []
stories = []
current_title = None
current_story = []

for section in sections:
  section = section.strip()
  if not section:
    continue
  if len(section) < 100 and '.' not in section:
    if current_title and current_story:
      stories.append(' '.join(current_story))
      titles.append(current_title)
    current_title = section
    current_story = []
  else: current_story.append(section)

# add last story to list of stories
if current_title and current_story:
  stories.append(' '.join(current_story))
  titles.append(current_title)

# create dataframe
text_df = pd.DataFrame({'title': titles, 'story': stories})
print(f"parsed {len(text_df)} stories from text dataset")

text_df.describe()

text_df.info()

print(text_df.shape)

# get number of sentences
text_df['num_sentences'] = text_df['story'].apply(lambda x: len([s for s in x.split('.') if s.strip()]))

# number of words
text_df['num_words'] = text_df['story'].apply(lambda x: len(x.split()))

# average words per sentence
text_df['average_words'] = text_df['num_words'] / text_df['num_sentences']

plt.figure(figsize=(12,5))
sns.histplot(text_df['num_words'], bins=30, kde=True)
plt.title('Distribution of Story Length, by Words')
plt.xlabel('Number of Words')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12,5))
sns.histplot(text_df['num_sentences'], bins=30, kde=True, color='purple')
plt.title('Distribution of Story Length, by Sentences')
plt.xlabel('Number of Sentences')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12,5))
sns.histplot(text_df['average_words'], bins=30, kde=True, color='green')
plt.title('Distribution of Average Number of Words per Sentence')
plt.xlabel('Average Number of Words per Sentence')
plt.ylabel('Frequency')
plt.show()

from collections import Counter

all_words = ' '.join(text_df['story']).split()
word_counts = Counter(all_words)
common_words = word_counts.most_common(20)

# convert to data frame
common_df = pd.DataFrame(common_words, columns=['word','count'])

plt.figure(figsize=(12,6))
sns.barplot(x='count', y='word', data=common_df, color='teal')
plt.title('Top 20 Most Common Words')
plt.show()

text_df['num_unique_words'] = text_df['story'].apply(lambda x: len(set(x.split())))

plt.figure(figsize=(12,5))
sns.histplot(text_df['num_unique_words'], bins=30, kde=True, color='plum')
plt.title('Distribution of Unique Words')
plt.xlabel('Unique Words')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10,6))
sns.scatterplot(x='num_words', y='num_unique_words', data=text_df)
plt.title('Unique Words vs Overall Number of Words per Story')
plt.xlabel('Number of Words')
plt.ylabel('Number of Unique Words')
plt.show()