# -*- coding: utf-8 -*-
"""milestone3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7lbnsJ9hgvZqZBGUlBk_qGtr6iKDUxt
"""

from google.colab import drive
drive.mount('/content/gdrive')

"""## Children Stories Text Corpus Dataset"""

import pandas as pd
import numpy as np
import re

with open('/content/gdrive/MyDrive/cleaned_merged_fairy_tales_without_eos.txt', 'r', encoding='utf-8') as f:
    text_data = f.read()

# split text data
sections = text_data.split("\n\n")

titles = []
stories = []
current_title = None
current_story = []

for section in sections:
  section = section.strip()
  if not section:
    continue
  if len(section) < 100 and '.' not in section:
    if current_title and current_story:
      stories.append(' '.join(current_story))
      titles.append(current_title)
    current_title = section
    current_story = []
  else: current_story.append(section)

# add last story to list of stories
if current_title and current_story:
  stories.append(' '.join(current_story))
  titles.append(current_title)

# create dataframe
text_df = pd.DataFrame({'title': titles, 'story': stories})
print(f"parsed {len(text_df)} stories from text dataset")

text_df.describe()

text_df.info()

print(text_df.shape)

text_df

# get number of sentences
text_df['num_sentences'] = text_df['story'].apply(lambda x: len([s for s in x.split('.') if s.strip()]))

# number of words
text_df['num_words'] = text_df['story'].apply(lambda x: len(x.split()))

# average words per sentence
text_df['average_words'] = text_df['num_words'] / text_df['num_sentences']

"""## Internal Safety Filter

Currently, the Project LibrAIrian employs a safety filter that screens generated responses before they are shown to the user. For Milestone 3, we decided to this method to include an internal safety filter that screens the text content in our book database before the model uses it. This ensures that any unsafe or inappropriate passages are removed or flagged, preventing them from being included in responses. Alternatively, our team also conducted a careful manual review of all books in the database to ensure that no harmful content is present.
"""

# examples of unsafe, toxic words
unsafe_words = [
    "suicide", "self-harm", "hate speech", "racist", "violence",
    "extremism", "graphic", "gore"
]

def screen_text_internal(text: str) -> str:
    """
    Remove unsafe or flagged sections from book text.
    Returns cleaned text.
    """
    cleaned = text
    for keyword in unsafe_words:
        cleaned = re.sub(keyword, "[REMOVED_FOR_SAFETY]", cleaned, flags=re.IGNORECASE)
    return cleaned

"""## Book Database"""

book_database = []
for _, row in text_df.iterrows():
    cleaned_story = screen_text_internal(row['story'])
    # Only include stories that are safe after filtering
    if "[REMOVED_FOR_SAFETY]" not in cleaned_story:
        book_database.append({
            "title": row['title'],
            "content": cleaned_story
        })
    else:
        # skip unsafe story
        pass

def find_book(title: str):
    """
    Search for a book by title in the database.
    Returns the book dictionary if found.
    """
    for book in book_database:
        if book["title"].lower() == title.lower():
            return book
    return None

def chatbot_response(user_question: str) -> str:
    """
    Responds using book-aware knowledge.
    If book not found, responds using themes from available stories.
    """
    # Try exact or fuzzy match for book titles
    titles = [book["title"] for book in book_database]
    matches = get_close_matches(user_question, titles, n=1, cutoff=0.5)

    if matches:
        book_data = find_book(matches[0])
        return f"In '{book_data['title']}', the text says: {book_data['content'][:300]}..."
    else:
        return "I don’t have access to that book, but I can try to answer your question using similar themes in the stories I have."

"""Our Project LibrAIrian is designed to provide book aware responses using a database of children's stories. When a user asks a question in reference to a book in the database, Project LibrAIrian would retrieve and cute the relevant text, clearly indicating which parts come directly from that book. This would then ensure that users receive accurate and context-specific information. However, if the user asks about a book that is not included in the database, Project LibrAIrian would still be able to try and answer the question, but with a disclaimer such as “I don' have access to that book, but I can answer based on similar themes in the books I do have.” This approach would allow Project LibrAIrian to remain informative while being transparent about the limits of its knowledge.

## Example
"""

if __name__ == "__main__":
    user_questions = [
        "What happens in A Thanksgiving Story?",
        "Tell me about Sleeping Beauty."
    ]

    for q in user_questions:
        print("User:", q)
        print("Bot:", chatbot_response(q))
        print("-" * 40)

"""##"""