# -*- coding: utf-8 -*-
"""rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pbw8ZpZm8MMM-VUbXG9v0cNaj73tQroN
"""

import re, math
import pandas as pd
from sentence_transformers import SentenceTransformer
import numpy as np
import torch
import time
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity

class KidsRAG:
  def __init__(self,
               data_path,
               passage_size,
               embed_batch_size=128,
               model_name="all-MiniLM-L6-v2",
               output_dir="./output_data"):

    self.data_path = Path(data_path)
    self.passage_size = passage_size
    self.model_name = model_name
    self.output_dir = Path(output_dir)
    self.output_dir.mkdir(parents=True, exist_ok=True)

    self.device = "cuda" if torch.cuda.is_available() else "cpu"
    print("Using device", self.device)

    self.embed_batch_size = embed_batch_size
    self.embed_model = SentenceTransformer(model_name)

    self.passages_df = None
    self.embeddings = None

  def load_data(self):
    # try to split into candidate stories
    with open(self.data_path, "r", encoding="utf-8", errors="replace") as fh:
      return fh.read()

  def _passage_text(self, text):
    words = text.split()

    passages = []
    for i in range(0, len(words), self.passage_size):
      passage = " ".join(words[i:i+self.passage_size]).strip()
      if len(passage) > 20:
        passages.append(passage)

    return passages

  def chunk_data(self, text):
    # split on multiple newlines
    story_blocks = [b.strip() for b in re.split(r'\n{2,}', text) if len(b.strip())>50]

    rows = []
    for si, block in enumerate(story_blocks):
      title = f"story_{si}"
      passages = self._passage_text(block)
      for j, c in enumerate(passages):
        rows.append({"story_id": si, "title": title, "passage_id": f"{si}_{j}", "passage": c})

    passages_df = pd.DataFrame(rows)

    return passages_df

  def embed_passages(self, passages_df):
    passages = passages_df['passage'].tolist()
    total_passages = len(passages)

    # compute embeddings with batching
    batch_size = self.embed_batch_size
    embeddings = []

    start_time = time.time()
    for i in range(0, total_passages, batch_size):
      batch = passages[i:i+batch_size]
      batch_embeddings = self.embed_model.encode(
          batch,
          convert_to_numpy=True,
          show_progress_bar=False
      )
      embeddings.append(batch_embeddings)

    # combine all batches
    embeddings = np.vstack(embeddings)
    end_time = time.time()
    print("Embedding computation time:", round(end_time - start_time, 1), "s")

    return embeddings

  def save_results(self):
    # save final embeddings
    if  self.passages_df is None or self.embeddings is None:
      raise RuntimeError("RAG passages not prepared for saving. Try calling rag.prepare_data().")
    np.save(self.output_dir / "embeddings.npy", self.embeddings)
    self.passages_df.to_pickle(self.output_dir / "passages.pkl")

  def load_saved_passages(self):
    passages_path = self.output_dir / "passages.pkl"
    if passages_path.exists():
      self.passages_df = pd.read_pickle(passages_path)

      return True

    return False

  def load_saved_embeddings(self):
    embeddings_path = self.output_dir / "embeddings.npy"

    if embeddings_path.exists():
      self.embeddings = np.load(embeddings_path)

      return True

    return False

  def prepare_data(self):
    passages_loaded = self.load_saved_passages()
    embeddings_loaded = self.load_saved_embeddings()
    if passages_loaded and embeddings_loaded:
      return

    raw_text = self.load_data()
    self.passages_df = self.chunk_data(raw_text)
    self.embeddings = self.embed_passages(self.passages_df)

    self.save_results()

  def retrieve_passages(self, query, top_k=3, subset_df=None, subset_embeddings=None):
    if subset_df is not None and subset_embeddings is not None:
      df = subset_df
      embeddings = subset_embeddings
    else:
      df = self.passages_df
      embeddings = self.embeddings

    if df is None or embeddings is None:
      raise RuntimeError("RAG passages not prepared. Try calling rag.prepare_data().")

    query_vec = self.embed_model.encode([query], convert_to_numpy=True)
    sims = cosine_similarity(query_vec, embeddings)[0]
    top_indices = sims.argsort()[-top_k:][::-1]

    return df.iloc[top_indices].copy()