# -*- coding: utf-8 -*-
"""rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pbw8ZpZm8MMM-VUbXG9v0cNaj73tQroN
"""

import re, math
import pandas as pd
from sentence_transformers import SentenceTransformer
import numpy as np
import torch
import time
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity
from output_filter import OutputFilter

# Retrieval Augmented Generation / RAG class for children's story content
class KidsRAG:
  def __init__(self, # initialize KidsRAG pipeline
               data_path, # path to raw text file containing story data
               passage_size, # number of words per passage chunk
               embed_batch_size=128,
               model_name="all-MiniLM-L6-v2",
               output_dir="./output_data", # directory used to cache embeddings and passages
               datacard_titles_path=None):

    self.data_path = Path(data_path)
    self.passage_size = passage_size
    # name of SentenceTransformer model
    self.model_name = model_name
    # directory for saving passages and embeddings
    self.output_dir = Path(output_dir)
    self.output_dir.mkdir(parents=True, exist_ok=True)

    # select device for embedding computation
    self.device = "cuda" if torch.cuda.is_available() else "cpu"
    print("Using device", self.device)

    self.embed_batch_size = embed_batch_size
    # sentence embedding model used for passage and query embeddings
    self.embed_model = SentenceTransformer(model_name)

    # DataFrame containing passage text and metadata
    self.passages_df = None
    self.embeddings = None
    
    self.approved_titles = self.load_approved_titles(datacard_titles_path)

  def load_data(self):
    # try to split into candidate stories
    # load raw story data
    with open(self.data_path, "r", encoding="utf-8", errors="replace") as fh:
      return fh.read()
      
  def load_approved_titles(self, path):
    """
    Load and normalize list of approved story titles.
    Allows restricting of corpus to predefined set of stories
    """
    if path is None:
        return None
    
    data_path = Path(path)
    
    text = data_path.read_text(encoding="utf-8")
    titles = [line.strip() for line in text.splitlines() if line.strip()]
    
    titles_normalized = []
    for title in titles:
        title_text = title.strip('".!?') # for punctuation  
        title_normalized = re.sub(r"[^a-z0-9 ]","", title_text.lower())
        titles_normalized.append(title_normalized)
    
    return set(titles_normalized)
    

  def _passage_text(self, text):
    """Split block of text into word passages with a fixed size"""
    words = text.split()

    passages = []
    for i in range(0, len(words), self.passage_size):
      passage = " ".join(words[i:i+self.passage_size]).strip()
      if len(passage) > 20:
        passages.append(passage)

    return passages

  def chunk_data(self, text):
    # adapted from ada's milestone 3 file:
    """
    Parse raw text into stories, then chunk each story into passages
    """
    sections = text.split("\n\n")
    
    titles = []
    stories = []
    current_title = None
    current_story = []
    
    for section in sections:
      section = section.strip()
      if not section:
        continue
      
      lines = section.splitlines()
      first_line = lines[0].strip()
      
      title_candidate = False
      
      if first_line.isupper():
          title_candidate = True
      
      elif len(first_line) < 50 and first_line.endswith('.'):
          title_candidate = True
      
      first_line = first_line.strip('".!?') # for punctuation  
      first_line_normalized = re.sub(r"[^a-z0-9 ]","", first_line.lower())
      
      approved_title = False
      if first_line_normalized in self.approved_titles:
          approved_title = True
      
      if title_candidate and (approved_title==True or self.approved_titles is None):
        is_title = True
      else:
        is_title = False
    
      if is_title == True:    
        if current_title and current_story:
            stories.append(' '.join(current_story))
            titles.append(current_title)
        
        current_title = first_line_normalized
        current_story = lines[1:] if len(lines) > 1 else []
      
      else:
          current_story.extend(lines)
    
    # add last story to list of stories
    if current_title and current_story:
      stories.append(' '.join(current_story))
      titles.append(current_title)
      
    passages = []
    for x in range(len(stories)):
        title = titles[x].strip() # for whitespace
        chunks = self._passage_text(stories[x])
        
        for i, passage in enumerate(chunks):
            passages.append({"title":title,
                "passage": passage})

    passages_df = pd.DataFrame(passages)

    return passages_df

  def embed_passages(self, passages_df):
    """
    Compute embeddings for all passages using batching
    """
    passages = passages_df['passage'].tolist()
    total_passages = len(passages)
    
    batch_size = self.embed_batch_size
    embeddings = []

    start_time = time.time()
    for i in range(0, total_passages, batch_size):
      batch = passages[i:i+batch_size]
      batch_embeddings = self.embed_model.encode(
          batch,
          convert_to_numpy=True,
          show_progress_bar=False
      )
      embeddings.append(batch_embeddings)

    # combine all batches
    embeddings = np.vstack(embeddings)
    end_time = time.time()
    print("Embedding computation time:", round(end_time - start_time, 1), "s")

    return embeddings

  def save_results(self):
    """Save passages and embeddings to disk for reuse"""
    if  self.passages_df is None or self.embeddings is None:
      raise RuntimeError("RAG passages not prepared for saving. Try calling rag.prepare_data().")
    np.save(self.output_dir / "embeddings.npy", self.embeddings)
    self.passages_df.to_pickle(self.output_dir / "passages.pkl")

  def load_saved_passages(self):
    """Load cached passages"""
    passages_path = self.output_dir / "passages.pkl"
    if passages_path.exists():
      self.passages_df = pd.read_pickle(passages_path)

      return True

    return False

  def load_saved_embeddings(self):
    """Load cached embeddings"""
    embeddings_path = self.output_dir / "embeddings.npy"

    if embeddings_path.exists():
      self.embeddings = np.load(embeddings_path)

      return True

    return False

  def prepare_data(self):
    """
    Prepare passages and embeddings, using cached data if possible
    """
    passages_loaded = self.load_saved_passages()
    embeddings_loaded = self.load_saved_embeddings()
    if passages_loaded and embeddings_loaded:
      return

    raw_text = self.load_data()
    self.passages_df = self.chunk_data(raw_text)
    self.embeddings = self.embed_passages(self.passages_df)

    self.save_results()

  def retrieve_passages(self, query, top_k=3, subset_df=None, subset_embeddings=None):
    """
    Retrieve the top k most similar passages for given query
    """
    if subset_df is not None and subset_embeddings is not None:
      df = subset_df
      embeddings = subset_embeddings
    else:
      df = self.passages_df
      embeddings = self.embeddings

    if df is None or embeddings is None:
      raise RuntimeError("RAG passages not prepared. Try calling rag.prepare_data().")

    query_vec = self.embed_model.encode([query], convert_to_numpy=True)
    sims = cosine_similarity(query_vec, embeddings)[0]
    top_indices = sims.argsort()[-top_k:][::-1]

    return df.iloc[top_indices].copy()
  
  def filter_passages(self, passages_df=None, text_column='passage',filter_obj=None, toxic_threshold=0.2, topic_threshold=0.6, dale_chall_file='dale_chall_words.txt'):
    """
    Apply output safety filters to remove unsafe passages
    """
    if passages_df is None:
      passages_df = self.passages_df
    if passages_df is None:
      raise RuntimeError("No passages to filter. Prepare or load passages first.")
  
    if filter_obj is None:
        # initialize filter
        filter_obj = OutputFilter(
          toxic_threshold=toxic_threshold,
          topic_threshold=topic_threshold,
          dale_chall_file=dale_chall_file
        )

    # apply filter to passages
    keep_rows = []
    for idx, row in passages_df.iterrows():
      text = row[text_column]
      result = filter_obj.filter(text)
      if not result['has_prohibited_topics'] and not result['is_toxic']:
        keep_rows.append(idx)
    
    filtered_df = passages_df.loc[keep_rows].reset_index(drop=True)
    return filtered_df
